In [1]:
import pandas as pd

In [17]:
df = pd.read_csv("../data/Spam_Email.csv")

In [3]:
df.head()

,CATEGORY,MESSAGE,FILE_NAME
0,1,"Dear Homeowner,\n\n \n\nInterest Rates are at ...",00249.5f45607c1bffe89f60ba1ec9f878039a
1,1,ATTENTION: This is a MUST for ALL Computer Use...,00373.ebe8670ac56b04125c25100a36ab0510
2,1,This is a multi-part message in MIME format.\n...,00214.1367039e50dc6b7adb0f2aa8aba83216
3,1,IMPORTANT INFORMATION:\n\n\n\nThe new domain n...,00210.050ffd105bd4e006771ee63cabc59978
4,1,This is the bottom line. If you can GIVE AWAY...,00033.9babb58d9298daa2963d4f514193d7d6

In [4]:
df.shape

(5796, 3)

In [18]:
df = df[["CATEGORY", "MESSAGE"]]

In [23]:
df.head()

   CATEGORY                                            MESSAGE
0         1  Dear Homeowner,\n\n \n\nInterest Rates are at ...
1         1  ATTENTION: This is a MUST for ALL Computer Use...
2         1  This is a multi-part message in MIME format.\n...
3         1  IMPORTANT INFORMATION:\n\n\n\nThe new domain n...
4         1  This is the bottom line.  If you can GIVE AWAY...

In [75]:
df.isnull().sum()

CATEGORY    0
MESSAGE     0
dtype: int64

In [76]:
df.duplicated().sum()

np.int64(171)

In [19]:
df.drop_duplicates(inplace=True)

In [11]:
df["CATEGORY"].value_counts()

CATEGORY
0    3862
1    1763
Name: count, dtype: int64

In [ ]:
from bs4 import BeautifulSoup # Библиотека для парсинга HTML и XML документов

In [20]:
df["MESSAGE"] = df["MESSAGE"].apply(lambda x: BeautifulSoup(x, "html.parser").get_text(separator=" "))
# df["MESSAGE"] = df["MESSAGE"].apply(lambda x: BeautifulSoup(x, "lxml").get_text(separator=" "))

In [ ]:
# import re

In [ ]:
# Удаление HTML элементов с использованием regex
# def remove_html_regex(text):
#     # 1. Удаляем блоки <script> и <style> вместе с содержимым
#     clean = re.sub(r'<(script|style).*?>.*?</\1>', ' ', text, flags=re.DOTALL)
#     # 2. Удаляем все остальные HTML-теги
#     clean = re.sub(r'<[^>]+>', ' ', clean)
#     # 3. Схлопываем лишние пробелы
#     return re.sub(r'\s+', ' ', clean).strip()

In [ ]:
# df["MESSAGE"] = df["MESSAGE"].apply(remove_html_regex)

In [ ]:
df.duplicated().sum()

np.int64(42)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
# import nltk
# from nltk.tokenize import word_tokenize
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer

# nltk.download('punkt_tab')
# nltk.download('stopwords')
# nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Yernar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Yernar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
# stop_words = set(stopwords.words('english'))
# lemma = WordNetLemmatizer()

# def preprocess_text(text):
#     # Lowercase the text
#     text = text.lower()
    
#     # Remove punctuation and special characters
#     text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    
#     # Remove extra whitespace
#     text = re.sub(r'\s+', ' ', text).strip()

#     tokens = word_tokenize(text)
    
#     tokens = [token for token in tokens if token not in stop_words]

#     tokens = [lemma.lemmatize(token) for token in tokens]

#     return ' '.join(tokens)

In [ ]:
import spacy # Предпочтительнее чем nltk
# python -m spacy download en_core_web_sm

In [ ]:
nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"]) # Отключение parser и ner при загрузке для ускорения пайплайна

def preprocess_text(text):

    doc = nlp(text) # Токенизация и лемматизация с помощью spaCy

    tokens = []
    for token in doc:
        if token.is_stop or token.is_punct or token.is_space: # Если токен является стоп-словом, пунктуацией или пробелом, пропускаем его
            continue
        if token.like_num: # Если токен является числом, пропускаем его
            continue
        lemma = token.lemma_.lower().strip() # Приводение леммы к нижнему регистру и удаление пробелов

        if lemma.isalpha() and len(lemma) > 1:
            tokens.append(lemma)

    return ' '.join(tokens)

In [26]:
df['MESSAGE'] = df['MESSAGE'].apply(preprocess_text)

In [27]:
df.head()

   CATEGORY                                            MESSAGE
0         1  dear homeowner interest rates low point year h...
1         1  attention computer users new special package d...
2         1  multi message mime format content type text pl...
3         1  important information new domain name finally ...
4         1  line away cd free people like month let talk a...

In [28]:
df.duplicated().sum()

np.int64(333)

In [29]:
df.drop_duplicates(inplace=True)

In [ ]:
df['MESSAGE'] = df['MESSAGE'].fillna('')

In [ ]:
df.to_csv('../data/Spam_Email_cleaned.csv', index=False)